minor additions
AdityaPrakash-26/450dsa pull request #1
Opened 2021-08-04 18:21 UTC by ComputerScientist-01

feel free to see my solutions

2021-08-04 18:51 UTC, AdityaPrakash-26 requested changes
Other than the `README.md`, everything LGTM!

2021-08-04 18:51 UTC, AdityaPrakash-26 commented on Jayvardhan/README.md
> +<h3 align="right">Built with :heart: by Jayvardhan Rathi</h3>
Please undo this change

2021-08-05 04:39 UTC, ComputerScientist-01 commented on Jayvardhan/README.md
> +<h3 align="right">Built with :heart: by Jayvardhan Rathi</h3>
readme has been removed

2021-08-05 04:46 UTC, AdityaPrakash-26 commented
LGTM!

2021-08-05 04:47 UTC, merged